### ISSUE TITLE
Get Config File Working

### ISSUE THREAD

**Issue by pennmeg** [pennmeg/a11y-actions#12]
Documentation mentions being able to configure your environment (and repo) with custom rules for components, as well as turning linting features on/off. 

```
global-components:
  CustomImage:
    element: img
    attributes:
    - altText: alt
rules:
  tabindex: false
```
